## Numpy

NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices,
along with a collection of mathematical functions to operate on these data structures. In this lesson, we will
cover the basics of NumPy, focusing on arrays and vectorized operations.

In [1]:
! pip install numpy 

Defaulting to user installation because normal site-packages is not writeable


In [5]:
import numpy as np 

# creating a array as a numpy 
# create a 1-D array 

arr1 = np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))
# if i need to show the shape by usnig the shape 
print(arr1.shape)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [ ]:
arr2 = np.array([1,2,3,4,5,6])
arr2.reshape(1,6)

# array([[1, 2, 3, 4, 5, 6]]) it is a 2 dimension array 

array([[1, 2, 3, 4, 5, 6]])

In [10]:
# craeting a 2d array 

arr3 = np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(arr3)
print(arr3.shape)

[[1 2 3 4 5]
 [5 6 7 8 9]]
(2, 5)


In [ ]:
# if i am using the arange it should do nothing it shows that how many elements you need to show or how amny stpes you skips 

np.arange(0,10,3)
# array([0, 3, 6, 9])   ye rha h iska output

array([0, 3, 6, 9])

In [ ]:
# np.ones( ye hume  batata hi ki hume single digit ke kitne row or kitne columns create kerna h or sare ones ke hi hoge. )

np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [15]:
# identity matrix 

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("array\n",arr)
print("shape",arr.shape)
print("Number of dimension",arr.ndim)
print("size(number of elements):",arr.size)
print("Data Type",arr.dtype)
print("Item size(in bytes)",arr.itemsize)


array
 [[1 2 3 4]
 [5 6 7 8]]
shape (2, 4)
Number of dimension 2
size(number of elements): 8
Data Type int32
Item size(in bytes) 4


In [22]:
# numpy Vectorize Operations 

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# element wise addition 
print("Addition:",arr1+arr2)

# element wise subtraction 
print("Subtraction:",arr2-arr1)

# element wise mulltipication 
print("Subtraction:",arr2*arr1)

# element wise division 
print("Subtraction:",arr2/arr1)


Addition: [11 22 33 44 55]
Subtraction: [ 9 18 27 36 45]
Subtraction: [ 10  40  90 160 250]
Subtraction: [10. 10. 10. 10. 10.]


In [ ]:
# universal FUnction 
arr = np.array([1,2,3,4,5])
# square root
print("square root",np.sqrt(arr))

# exponantial 
print("exponantial",np.exp(arr))

# sin theta
print("sine",np.sin(arr))

# natural log

print("natural log",np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [29]:
# arrray slicing and indexing 

arr = np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
arr



array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [31]:
# mujhe ab uske ander ke elments ko acess kerna h

arr[0,3]

40

In [ ]:
# agr mujhe sirf 70 80,110, 120 tak ka hi elelment chahiye to kya kerunga 
arr[1:,2:]
# ist row ka 2nd element ko acess kerna h 


array([[ 70,  80],
       [110, 120]])

In [ ]:
# ab 30 se 80 tak ka chahiye to kya kerunga
arr[0:2,1:]
# 0 row se 2nd elemnt ko pick kiya or 1st row ke last  element  tak ka dekha 

array([[20, 30, 40],
       [60, 70, 80]])

In [41]:
# ab mujhe 60 or 70 h chahiye
arr[1:,1:3]

array([[ 60,  70],
       [100, 110]])

In [42]:
# modify th array elements 
arr[0,0] = 1000
print(arr)


[[1000   20   30   40]
 [  50   60   70   80]
 [  90  100  110  120]]


In [43]:
# agr sabhi ko ek jaisa banana h to 
arr[1:]=10000
print(arr)

[[ 1000    20    30    40]
 [10000 10000 10000 10000]
 [10000 10000 10000 10000]]


In [44]:
# statical concept and normalization

# to have a mean of 0 and standard deviation  of 1 

# so clculate the mean and standard deviation ?

data = np.array([1,2,3,4])

mean = np.mean(data)
std_dev = np.std(data)

# normalize the data 

"fomula"
normalize_data = (data-mean)/std_dev

print("normalized data : \n",normalize_data)



normalized data : 
 [-1.34164079 -0.4472136   0.4472136   1.34164079]


In [ ]:
# mean , median ,std,varience

data = np.array([1,2,3,4,5,6,7,8,9,10])

# mean 
mean = np.mean(data)
print("mean \n",mean)

# median 
median = np.median(data)
print("median \n",median)

# std  (standard deviation)
std_dev = np.std(data)
print("standard deviation \n",std_dev)

# variennce

vari = np.var(data)
print("Varience",vari)


mean 
 5.5
median 
 5.5
standard deviation 
 2.8722813232690143
Varience 8.25


In [53]:
# Logical Operation

data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5)&(data<=9)]

array([5, 6, 7, 8, 9])